### NumPy has many functions that are useful in data science, but some of the most important ones are:

### 1. Creating arrays:

In [ ]:
import numpy as np

# Creating a 1-dimensional array
a = np.array([1, 2, 3, 4, 5])
print(a)
# Output: [1 2 3 4 5]

# Creating a 2-dimensional array of zeros
b = np.zeros((3, 3))
print(b)
# Output: 
# [[0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]

# Creating a 2-dimensional array of ones
c = np.ones((2, 4))
print(c)
# Output: 
# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]]

# Creating a 3-dimensional array of a specific value
d = np.full((2, 3, 2), 7)
print(d)
# Output: 
# [[[7 7]
#   [7 7]
#   [7 7]]

#  [[7 7]
#   [7 7]
#   [7 7]]]

# Creating a range of values
e = np.arange(1, 10, 2)
print(e)
# Output: [1 3 5 7 9]

# Creating a range of values with a specific number of elements
f = np.linspace(0, 1, 11)
print(f)
# Output: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

# Creating a 2-dimensional array of random values
g = np.random.rand(3, 2)
print(g)
# Output:
# [[0.73257041 0.58599762]
#  [0.54583407 0.2979637 ]
#  [0.26041177 0.34908936]]

# Creating a 2-dimensional array of random values with a normal distribution
h = np.random.randn(4, 4)
print(h)
# Output:
# [[-1.40683653 -0.7360157  -1.21193636 -0.15139244]
#  [ 1.27435647  0.38893684 -0.56260329 -1.67093311]
#  [-1.41269874 -0.78907992 -0.49535822 -0.37206563]
#  [ 1.18436094 -0.28831246 -0.61867705 -0.60206844]]

### Basic operations:

In [ ]:
# Adding two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.add(a, b)
print(c)
# Output: [5 7 9]

# Subtracting two arrays
d = np.subtract(b, a)
print(d)
# Output: [3 3 3]

# Multiplying two arrays
e = np.multiply(a, b)
print(e)
# Output: [ 4 10 18]

# Dividing two arrays
f = np.divide(b, a)
print(f)
# Output: [4.  2.5 2. ]

# Dot product of two arrays
g = np.dot(a, b)
print(g)
# Output: 32

# Sum of array elements
h = np.sum(a)
print(h)
# Output: 6

# Mean of array elements
i = np.mean(b)
print(i)
# Output: 5.0

# Maximum value of array elements
j = np.max(a)
print(j)
# Output: 3

# Minimum value of array elements
k = np.min(b)
print(k)
# Output: 4

# Standard deviation of array elements
l = np.std(a)
print(l)
# Output: 0.816496580927726

### Array indexing and slicing:

In [ ]:
# Indexing a 1-dimensional array
a = np.array([1, 2, 3])
b = a[1]
print(b)
# Output: 2

# Indexing a 2-dimensional array
c = np.array([[1, 2, 3], [4, 5, 6]])
d = c[0, 1]
print(d)
# Output: 2

# Adding a new axis to an array
e = np.array([1, 2, 3])
f = e[np.newaxis, :]
print(f)
# Output: [[1 2 3]]

# Finding the indices of array elements that meet a condition
g = np.array([1, 2, 3, 4, 5])
h = np.where(g > 3)
print(h)
# Output: (array([3, 4]),)

# Finding the indices of non-zero elements in an array
i = np.array([0, 2, 0, 4, 0])
j = np.nonzero(i)
print(j)
# Output: (array([1, 3]),)

# Finding the unique elements in an array
k = np.array([1, 2, 3, 3, 2, 1])
l = np.unique(k)
print(l)
# Output: [1 2 3]

# Sorting an array
m = np.array([3, 2, 1])
n = np.sort(m)
print(n)
# Output: [1 2 3]

### Shape manipulation:

In [ ]:
# Reshaping an array
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.reshape(a, (2, 3))
print(b)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Flattening an array
c = a.flatten()
print(c)
# Output:
# [1 2 3 4 5 6]

# Transposing an array
d = np.transpose(a)
print(d)
# Output:
# [[1 3 5]
#  [2 4 6]]

# Horizontally stacking arrays
e = np.hstack((a, a))
print(e)
# Output:
# [[1 2 1 2]
#  [3 4 3 4]
#  [5 6 5 6]]

# Vertically stacking arrays
f = np.vstack((a, a))
print(f)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [1 2]
#  [3 4]
#  [5 6]]

# Splitting an array
g = np.array([1, 2, 3, 4, 5, 6])
h = np.split(g, 3)
print(h)
# Output:
# [array([1, 2]), array([3, 4]), array([5, 6])]

# Concatenating arrays
i = np.concatenate((a, a), axis=1)
print(i)
# Output:
# [[1 2 1 2]
#  [3 4 3 4]
#  [5 6 5 6]]

### Mathematical functions:

In [ ]:
# Trigonometric functions
a = np.array([0, np.pi/2, np.pi])
b = np.sin(a)
print(b)  # Output: [0.         1.         0.        ]
c = np.cos(a)
print(c)  # Output: [ 1.000000e+00  6.123234e-17 -1.000000e+00]

# Exponential and logarithmic functions
d = np.exp(a)
print(d)  # Output: [ 1.          4.48168907 23.14069263]
e = np.log(a)
print(e)  # Output: [-inf  0.          1.14472989]

# Square root and power functions
f = np.sqrt(a)
print(f)  # Output: [0.         1.25331414 1.77245385]
g = np.power(a, 2)
print(g)  # Output: [0.         2.4674011  9.8696044 ]

# Absolute function
h = np.abs(a)
print(h)  # Output: [0.         1.57079633 3.14159265]

### Linear algebra:

In [ ]:
# Inverse of a matrix
a = np.array([[1, 2], [3, 4]])
b = np.linalg.inv(a)
print(b)
# Output:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# Determinant of a matrix
c = np.linalg.det(a)
print(c)
# Output:
# -2.0000000000000004

# Eigenvalues and eigenvectors of a matrix
d, e = np.linalg.eig(a)
print(d)
print(e)
# Output:
# [-0.37228132  5.37228132]
# [[-0.82456484 -0.41597356]
#  [ 0.56576746 -0.90937671]]

# Singular Value Decomposition (SVD) of a matrix
f, g, h = np.linalg.svd(a)
print(f)
print(g)
print(h)
# Output:
# [[-0.40455358 -0.9145143 ]
#  [-0.9145143   0.40455358]]
# [5.4649857  0.36596619]
# [[-0.57604844 -0.81741556]
#  [-0.81741556  0.57604844]]

# Solving a system of linear equations
i = np.array([[2, 1], [1, 1]])
j = np.array([6, 4])
k = np.linalg.solve(i, j)
print(k)
# Output:
# [2. 4.]

### I hope these examples are helpful to you.